//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestInfo
    {
        public int Gid { get; set; }
        public string Gname { get; set; }
        public int GTid { get; set; }
        public string Sex { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> ChargeSum { get; set; }
        public string Pid { get; set; }
    }
}
